# Generated by Django 5.0.6 on 2024-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_botinforamtion_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinforamtion',
            name='botdescription',
            field=models.CharField(default='my girlfriend', max_length=255),
        ),
    ]
